---
- name: Ensure apt is using HTTPS
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Create keyrings folder
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'  # Optional file permissions
    owner: aclaretdev  # Optional ownership
    group: aclaretdev  # Optional group ownership

- name: Change permissions of docker key file
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    state: touch
    mode: 'a+r'

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: /etc/apt/keyrings/docker.asc
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Ensure Docker service is enabled and running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Ensure docker-compose is installed
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Create "docker" group
  ansible.builtin.group:
    name: "{{ docker_group }}"
    state: present

- name: Add remote "ubuntu" user to "docker" group
  ansible.builtin.user:
    name: "{{ remote_admin_user }}"
    group: "{{ docker_group }}"
    append: true
