---
- name: Tibia-Mkt localhost create artifact
  hosts: localhost
  roles:
    - tibia-mkt-zip

- name: Deploy tibia-mkt to hosts
  hosts: all
  become: true
  roles:
    - docker-install
    - tibia-mkt-build
