---
- name: Tibia-Mkt localhost create artifact
  hosts: localhost
  roles:
    - tibia-mkt-zip

- name: Deploy tibia-mkt to hosts
  hosts: all
  become: true
  roles:
    - docker-install
    - tibia-mkt-build
    - tibia-mkt-set-env-vars
    - tibia-mkt-run
    - tibia-mkt-run-migrations
  environment:
    DATABASE_IP: "{{ database_ip }}"
    DATABASE_NAME: "{{ database_name }}"
    DATABASE_USER: "{{ database_user }}"
    DATABASE_PASSWORD: "{{ database_password }}"
    SERVER_PORT: "{{ server_port }}"
    TIBIA_MKT_API_KEY: "{{ tibia_mkt_api_key }}"
    ENVIRONMENT: "PRODUCTION"
    API_URL: "{{ api_url }}"
    API_PROTOCOL: "{{ api_protocol }}"
