---
- name: Import global vars
  ansible.builtin.include_vars: main.yml

- name: Create tmp build folder
  ansible.builtin.file:
    path: "{{ tmp_build_folder }}"
    state: directory
    mode: '0755'  # Optional file permissions
    owner: aclaretdev  # Optional ownership
    group: aclaretdev  # Optional group ownership

- name: Copy tibia-mkt artifact to tmp_build folder
  ansible.builtin.copy:
    src: "{{ local_tmp_project_folder }}/{{ tibia_mkt_artifact }}"
    dest: "{{ tmp_build_folder }}"
    mode: '0755'
    owner: aclaretdev  # Optional ownership
    group: aclaretdev  # Optional group ownership

- name: Copy tibia-mkt project to tmp_build folder
  ansible.builtin.unarchive:
    src: "{{ tmp_build_folder }}/{{ tibia_mkt_artifact }}"
    dest: "{{ tmp_build_folder }}"
    mode: '0755'
    owner: aclaretdev  # Optional ownership
    group: aclaretdev  # Optional group ownership
