---
- name: Import global vars
  ansible.builtin.include_vars:
    dir: /home/aclaret/CLARET-DEV/home-server/shared
    name: shared

- name: Remove tmp_build
  ansible.builtin.file:
    path: "{{ shared.tmp_build_folder }}"
    state: absent

- name: Create tmp build folder
  ansible.builtin.file:
    path: "{{ shared.tmp_build_folder }}"
    state: directory
    mode: '0755'  # Optional file permissions
    owner: aclaretdev  # Optional ownership
    group: aclaretdev  # Optional group ownership

- name: Copy tibia-mkt artifact to tmp_build folder
  ansible.builtin.copy:
    src: "{{ local_tmp_project_folder }}/{{ shared.tibia_mkt_artifact }}"
    dest: "{{ shared.tmp_build_folder }}"
    mode: '0755'
    owner: aclaretdev  # Optional ownership
    group: aclaretdev  # Optional group ownership

- name: Unzip tibia-mkt artifact
  ansible.builtin.unarchive:
    src: "{{ shared.tmp_build_folder }}/{{ shared.tibia_mkt_artifact }}"
    dest: "{{ shared.tmp_build_folder }}"
    remote_src: true
    mode: '0755'
    owner: aclaretdev  # Optional ownership
    group: aclaretdev  # Optional group ownership

- name: Remove .env files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ shared.tmp_build_folder }}/frontend/.env"
    - "{{ shared.tmp_build_folder }}/server/.env"
