---
- name: Import global vars
  ansible.builtin.include_vars:
    dir: /home/aclaret/CLARET-DEV/home-server/shared
    name: shared

- name: Run docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ shared.tmp_build_folder }}"
    state: present
    pull: missing
    build: always
    env_files:
      - .env
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
