---
- include_vars: /shared/shared-variables.yml

- name: Create tmp build folder
  ansible.builtin.file:
    path: "{{ local_tmp_build_folder }}"
    state: directory
    mode: '0755'

- name: Zip tibia-mkt app
  community.general.archive:
    path: "{{ local_project_folder }}"
    dest: "{{ local_tmp_build_folder }}/tibia-mkt-artifact.zip"
    mode: '0755'
